package view;

import DAO.ConexaoDAO;
import beans.Cadastro;
import javax.swing.JOptionPane;

public class PrincipalView extends javax.swing.JFrame {

    ConexaoDAO conectar = new ConexaoDAO(); //acessar os métodos de conexao com o banco
    Cadastro usuarioAtual = new Cadastro(); //acessar os atributos da classe Cadastro

    public PrincipalView() {
        initComponents();
    }

    private void buscarUsuario(Cadastro usuarioAtual) {
        this.conectar.conectaBD();

        String consultaUsuario = tfRecebe.getText();

        try {
            this.conectar.executarSQL(
                    "SELECT "
                    + "nome,"
                    + "nascimento,"
                    + "email,"
                    + "cidade,"
                    + "estado,"
                    + "faculdade,"
                    + "sexo,"
                    + "tipoSangue"
                    + " FROM"
                    + " cadastro"
                    + " WHERE"
                    + " email = '" + consultaUsuario + "'"
                    + ";"
            );
            while (this.conectar.getResultSet().next()) {
                usuarioAtual.setNome(this.conectar.getResultSet().getString(1));
                usuarioAtual.setNascimento(this.conectar.getResultSet().getString(2));
                usuarioAtual.setEmail(this.conectar.getResultSet().getString(3));
                usuarioAtual.setCidade(this.conectar.getResultSet().getString(4));
                usuarioAtual.setEstado(this.conectar.getResultSet().getString(5));
                usuarioAtual.setFaculdade(this.conectar.getResultSet().getString(6));
                usuarioAtual.setSexo(this.conectar.getResultSet().getString(7));
                usuarioAtual.setTipoSangue(this.conectar.getResultSet().getString(8));

            }
        } catch (Exception e) {
            System.out.println("Erro ao consultar usuário " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar usuário");
        } finally {

            consultaNome.setText(usuarioAtual.getNome());
            consultaNascimento.setText(usuarioAtual.getNascimento());
            consultaEmail.setText(usuarioAtual.getEmail());
            consultaCidade.setText(usuarioAtual.getCidade());
            consultaEstado.setText(usuarioAtual.getEstado());
            consultaFaculdade.setText(usuarioAtual.getFaculdade());
            consultaSexo.setText(usuarioAtual.getSexo());
            consultaTipoSangue.setText(usuarioAtual.getTipoSangue());
            this.conectar.fechaBanco();
        }

    }

    private void atualizarUsuario(Cadastro usuarioAtual) {
        this.conectar.conectaBD();

        String consultaUsuario = tfRecebe.getText();

        try {
            this.conectar.updateSQL(
                    "UPDATE cadastro SET "
                    + "nome = '" + consultaNome.getText() + "',"
                    + "nascimento = '" + consultaNascimento.getText() + "',"
                    + "email = '" + consultaEmail.getText() + "',"
                    + "cidade = '" + consultaCidade.getText() + "',"
                    + "estado = '" + consultaEstado.getText() + "',"
                    + "faculdade = '" + consultaFaculdade.getText() + "',"
                    + "sexo = '" + consultaSexo.getText() + "',"
                    + "tiposangue = '" + consultaTipoSangue.getText() + "'"
                    + " WHERE "
                    + "email = '" + consultaUsuario + "'"
                    + ";"
            );
        } catch (Exception e) {
            System.out.println("Erro ao atualizar usuario " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao atualizar cadastro");
        } finally {
            this.conectar.fechaBanco();
            JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso");
        }
    }

    private void deletarUsuario(Cadastro usuarioAtual) {

        this.conectar.conectaBD();

        String consultaUsuario = tfRecebe.getText();

        try {
            this.conectar.updateSQL(
                    "DELETE FROM cadastro "
                    + " WHERE "
                    + "email = '" + consultaUsuario + "'"
                    + ";"
            );
        } catch (Exception e) {
            System.out.println("Erro ao deletar usuario " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao deletar usuário");
        } finally {
            this.conectar.fechaBanco();
            JOptionPane.showMessageDialog(null, "Usuário deletado com sucesso");

            new LoginView().setVisible(true);
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        consultaNascimento = new javax.swing.JTextField();
        consultaNome = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        consultaCidade = new javax.swing.JTextField();
        consultaFaculdade = new javax.swing.JTextField();
        consultaTipoSangue = new javax.swing.JTextField();
        consultaSexo = new javax.swing.JTextField();
        consultaEstado = new javax.swing.JTextField();
        tfRecebe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        consultaEmail = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nascimento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        consultaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(consultaNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 230, -1));

        consultaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(consultaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 230, -1));

        btn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn.setText("Visualizar Dados");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cidade:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Faculdade:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipo Sanguíneo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        consultaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(consultaCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, -1));

        consultaFaculdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaFaculdadeActionPerformed(evt);
            }
        });
        getContentPane().add(consultaFaculdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, -1));

        consultaTipoSangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaTipoSangueActionPerformed(evt);
            }
        });
        getContentPane().add(consultaTipoSangue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 230, -1));

        consultaSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaSexoActionPerformed(evt);
            }
        });
        getContentPane().add(consultaSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 230, -1));

        consultaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(consultaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 230, -1));

        tfRecebe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfRecebe.setForeground(new java.awt.Color(255, 255, 255));
        tfRecebe.setText("LabelUsuario");
        getContentPane().add(tfRecebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 20));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Apagar Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 180, -1));

        btnSair.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 180, -1));

        consultaEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        consultaEmail.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(consultaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, 20));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Atualizar Cadastro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 170, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoprincipal.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaNascimentoActionPerformed

    private void consultaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaNomeActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        buscarUsuario(usuarioAtual);
    }//GEN-LAST:event_btnActionPerformed

    private void consultaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaCidadeActionPerformed

    private void consultaFaculdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFaculdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaFaculdadeActionPerformed

    private void consultaSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaSexoActionPerformed

    private void consultaTipoSangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaTipoSangueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaTipoSangueActionPerformed

    private void consultaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Object[] options = {"Confirmar", "Cancelar"};
        int confirma = JOptionPane.showOptionDialog(null, "Essa ação excluirá completamente seu cadastro, deseja continuar?", "Atenção",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (confirma == 0) {
            deletarUsuario(usuarioAtual);
        } else {
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        new LoginView().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        atualizarUsuario(usuarioAtual);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField consultaCidade;
    private javax.swing.JLabel consultaEmail;
    private javax.swing.JTextField consultaEstado;
    private javax.swing.JTextField consultaFaculdade;
    private javax.swing.JTextField consultaNascimento;
    private javax.swing.JTextField consultaNome;
    private javax.swing.JTextField consultaSexo;
    private javax.swing.JTextField consultaTipoSangue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tfRecebe;
    // End of variables declaration//GEN-END:variables
public void recebendo(String recebe) {
        tfRecebe.setText(recebe);
    }

}
